# Generated by Django 4.2 on 2023-04-25 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_transportation_lunch_dinner_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='userOwner',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrivalDay',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 25, 21, 22, 0, 137477, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='returnDay',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 25, 21, 22, 13, 851600, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
